language: R
r: bioc-devel
cache: packages
warnings_are_errors: true
after_script:
  - ls -lah
  - FILE=$(ls -1t *.tar.gz | head -n 1)
  - Rscript -e "library(BiocCheck); BiocCheck(\"${FILE}\")"
notifications:
  email:
    - oneillkza@gmail.com
